version: '3'

services:
  backend:
    build: 'SNS_backend'
    container_name: 'backend'
    ports:
       - '5000:5000'
    depends_on:
      - database
    restart: on-failure:10
  
  database:
    image: postgres:15.1
    environment:
      POSTGRES_DB: "DB_SNUS"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Defender02Sync02"
    volumes:
      - .:/docker-entrypoint-initdb.d
    restart: always
    expose:
      - '5432'

  bff:
      build: 'sns_bff/'
      container_name: 'bff'
      ports:
         - '8080:8080'
